# Generated by Django 4.2 on 2023-04-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_product_description_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
