# Generated by Django 4.2.11 on 2024-05-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_celerytask_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
