# Generated by Django 4.2.11 on 2024-05-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_celerytask_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
