# Generated by Django 4.1.7 on 2024-02-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
    ]
