# Generated by Django 4.1.7 on 2024-02-27 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr4', '0003_remove_country_president'),
    ]

    operations = [
        migrations.AlterField(
            model_name='president',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='pr4.country'),
        ),
    ]
