# Generated by Django 5.0 on 2024-03-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='cover_image',
            field=models.ImageField(default='manga_covers/Black_Bright.jpg', upload_to='manga_covers/'),
        ),
    ]
