# Generated by Django 4.2.1 on 2024-03-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_ingredient_remove_recipe_instructions_recipe_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="instruction",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes", to="recipes.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="time_required",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="time_required",
            field=models.IntegerField(default=10),
        ),
    ]
