# Generated by Django 4.2.1 on 2024-03-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_recipe_ingredients_instruction_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="instructions", to="recipes.ingredient"
            ),
        ),
    ]
