# Generated by Django 4.2.1 on 2024-03-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_category_rename_user_recipe_author_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(default=1),
        ),
    ]
