# Generated by Django 5.0.1 on 2024-01-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
