# Generated by Django 5.0.1 on 2024-01-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_movie_vote_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
