# Generated by Django 5.0.1 on 2024-01-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-release_date',)},
        ),
    ]
