# Generated by Django 5.0.1 on 2024-01-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-created_at',)},
        ),
    ]
