# Generated by Django 4.2.6 on 2024-02-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_city_accommodation_destination_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='departure_date',
            new_name='date',
        ),
    ]
