"""Creation Database

Revision ID: 968d5fbae062
Revises: 
Create Date: 2023-12-24 16:45:52.762660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968d5fbae062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
