# Generated by Django 3.2 on 2023-05-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_book_rating_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
