# Generated by Django 3.2 on 2023-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='book_title',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='sum',
            field=models.IntegerField(),
        ),
    ]
