# Generated by Django 3.2 on 2023-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230505_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
