# Generated by Django 2.1.1 on 2018-09-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_num_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='num_pages',
        ),
    ]
