# Generated by Django 4.2.4 on 2024-02-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('health', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('armor', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.unit')),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.unit',),
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('castle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.castle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='castle',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clan'),
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.unit')),
                ('castle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.castle')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.unit',),
        ),
    ]
