# Generated by Django 5.0.1 on 2024-03-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='books',
            field=models.ManyToManyField(related_name='publishers', to='myapp.book'),
        ),
    ]
