# Generated by Django 4.2.10 on 2024-03-07 08:25

from django.db import migrations, models
import django.db.models.deletion
import shiki.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('source', models.CharField(blank=True, choices=[('MANGA', 'Манга'), ('LIGHT_NOVEL', 'Лайт новелла')], max_length=255, null=True, verbose_name='Источник')),
                ('episodes', models.IntegerField(default=0, verbose_name='Количество эпизодов')),
                ('score', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('status', models.CharField(blank=True, choices=[('ONGOING', 'Онгоинг'), ('RELEASED', 'Выпущено')], max_length=255, verbose_name='Статус')),
                ('synopsis', models.TextField(blank=True, verbose_name='Синопсис')),
                ('is_adult', models.BooleanField(default=False, verbose_name='NSFW?')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/genre/', verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('volumes', models.IntegerField(default=0, verbose_name='Количество томов')),
                ('chapters', models.IntegerField(default=0, verbose_name='Количество глав')),
                ('score', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('status', models.CharField(blank=True, choices=[('ONGOING', 'Онгоинг'), ('RELEASED', 'Выпущено')], max_length=255, verbose_name='Статус')),
                ('synopsis', models.TextField(blank=True, verbose_name='Синопсис')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manga', to='shiki.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Манга',
                'verbose_name_plural': 'Манга',
            },
        ),
        migrations.CreateModel(
            name='LightNovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('volumes', models.IntegerField(default=0, verbose_name='Количество томов')),
                ('chapters', models.IntegerField(default=0, verbose_name='Количество глав')),
                ('score', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('status', models.CharField(blank=True, choices=[('ONGOING', 'Онгоинг'), ('RELEASED', 'Выпущено')], max_length=255, verbose_name='Статус')),
                ('synopsis', models.TextField(blank=True, verbose_name='Синопсис')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='light_novel', to='shiki.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Ранобэ',
                'verbose_name_plural': 'Ранобэ',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[shiki.utils.validate_size, shiki.utils.validate_extension], verbose_name='Изображение')),
                ('anime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anime_images', to='shiki.anime', verbose_name='Аниме')),
                ('light_novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='light_novel_images', to='shiki.lightnovel', verbose_name='Ранобэ')),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manga_images', to='shiki.manga', verbose_name='Манга')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='shiki.genre', verbose_name='Жанр'),
        ),
    ]
