# Generated by Django 4.2.10 on 2024-03-12 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiki', '0003_alter_anime_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='shiki.genre', verbose_name='Жанр'),
        ),
    ]
