# Generated by Django 5.0.1 on 2024-05-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_barbershop_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='sender',
        ),
        migrations.AlterField(
            model_name='applicationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('done', 'Done')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
