"""comm

Revision ID: 3961ebe05ba8
Revises: b210e99dffc9
Create Date: 2024-05-22 12:31:45.614089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3961ebe05ba8'
down_revision: Union[str, None] = 'b210e99dffc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('url', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('videos', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('videos', 'status')
    op.drop_column('videos', 'url')
    # ### end Alembic commands ###
