# Generated by Django 4.1.7 on 2024-05-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
