# Generated by Django 5.0.1 on 2024-03-02 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                ("airline_id", models.AutoField(primary_key=True, serialize=False)),
                ("airline_name", models.CharField(max_length=50)),
                ("airline_founded_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "city_population",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("short_name", models.CharField(max_length=10)),
                ("built_date", models.DateField()),
                (
                    "full_capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "economy_capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "business_capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "owner_airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.airline"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                ("airport_id", models.AutoField(primary_key=True, serialize=False)),
                ("airport_name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                (
                    "is_international",
                    models.BooleanField(
                        choices=[(True, "International"), (False, "Domestic")]
                    ),
                ),
                (
                    "city_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flight_fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_code", models.CharField(max_length=10)),
                ("dept_time", models.TimeField()),
                ("arr_time", models.TimeField()),
                (
                    "diff_days",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "airline_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.airline"
                    ),
                ),
                (
                    "airport_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="main.airport",
                    ),
                ),
                (
                    "airport_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivals",
                        to="main.airport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flight_dim",
            fields=[
                ("flight_id", models.AutoField(primary_key=True, serialize=False)),
                ("flight_date", models.DateField()),
                ("is_sale_open", models.BooleanField()),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.aircraft"
                    ),
                ),
                (
                    "flight_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.flight_fact",
                    ),
                ),
            ],
        ),
    ]
