# Generated by Django 5.0.1 on 2024-03-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_aircraft_aircraft_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="full_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
