# Generated by Django 5.0.1 on 2024-03-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_airport_airport_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Days_of_Week",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day", models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name="flight_fact",
            name="flight_days",
            field=models.ManyToManyField(to="main.days_of_week"),
        ),
    ]
