# Generated by Django 4.1.7 on 2024-04-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_to_emails',
            field=models.BooleanField(default=False),
        ),
    ]
