# Generated by Django 4.2 on 2023-04-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplines',
            options={'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='room_name',
        ),
    ]
