# Generated by Django 5.0.1 on 2024-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
