# Generated by Django 4.2 on 2023-04-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_events_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group'),
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
