# Generated by Django 4.2 on 2023-04-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_events_group_delete_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='discipline',
        ),
        migrations.AddField(
            model_name='events',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Disciplines',
        ),
    ]
