# Generated by Django 4.2 on 2023-04-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_events_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
    ]
