# Generated by Django 4.2 on 2023-04-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_room_name_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.organization'),
        ),
    ]
