# Generated by Django 4.2 on 2023-04-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_group_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='discipline',
        ),
    ]
