# Generated by Django 4.2 on 2023-04-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_group_organization'),
        ('api', '0014_rename_name_events_discipline'),
    ]

    operations = [
    ]
