# Generated by Django 4.2 on 2023-04-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20230420_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
