# Generated by Django 5.0.1 on 2024-03-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('model1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.model1')),
            ],
        ),
        migrations.CreateModel(
            name='Model3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model2', models.ManyToManyField(to='myapp.model2')),
            ],
        ),
        migrations.CreateModel(
            name='Model4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('model3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.model3')),
            ],
        ),
    ]
