# Generated by Django 4.2.6 on 2024-03-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('is_doctor', models.BooleanField(default=False)),
            ],
        ),
    ]
