# Generated by Django 5.0.2 on 2024-02-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_4', '0002_category_book_publisher_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='books',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
