# Generated by Django 5.0.2 on 2024-02-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='title',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='name',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
