# Generated by Django 4.2 on 2024-05-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars'), (6, '6 stars'), (7, '7 stars'), (8, '8 stars'), (9, '9 stars'), (10, '10 stars')]),
        ),
    ]
