# Generated by Django 4.2 on 2023-04-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_descr',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
