# Generated by Django 5.0.4 on 2024-05-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notification_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static\\images\\home-appliances.jpg', upload_to='category_images'),
        ),
    ]
