# Generated by Django 2.1.1 on 2018-09-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_num_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='a',
            new_name='city',
        ),
    ]
