# Generated by Django 4.1.2 on 2024-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
