# Generated by Django 4.1.7 on 2024-03-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_registration_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='quantity_available',
        ),
    ]
