# Generated by Django 4.1.7 on 2024-03-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ticket_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attendee'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
