# Generated by Django 4.1.7 on 2024-03-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_registration_attendee_alter_registration_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.AddField(
            model_name='ticket',
            name='attendee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.attendee'),
            preserve_default=False,
        ),
    ]
