# Generated by Django 4.1.7 on 2024-03-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_account_remove_comment_name_remove_organizer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attendee',
        ),
    ]
