# Generated by Django 4.1.7 on 2024-03-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_customuser_name_customuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
    ]
