# Generated by Django 4.1.7 on 2024-03-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_account_remove_organizer_account_organizer_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
