# Generated by Django 4.1.7 on 2024-03-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_account_schedule_organizer_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
