# Generated by Django 4.1.7 on 2024-03-11 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_account_organizer_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='account',
        ),
        migrations.AddField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
