# Generated by Django 4.1.7 on 2024-03-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_organizer_account_organizer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attendee'),
        ),
    ]
