# Generated by Django 4.1.5 on 2024-03-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Заголовок записи')),
                ('description', models.TextField(verbose_name='Текст записи')),
                ('date', models.DateField(verbose_name='Дата Публикации')),
                ('img', models.ImageField(upload_to='image/%Y', verbose_name='Изображение')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogApp.category')),
            ],
        ),
    ]
