# Generated by Django 4.2.6 on 2024-05-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='iin_bin',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_status',
            field=models.CharField(choices=[('Not Verified', 'Not Verified'), ('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Not Verified', max_length=100),
        ),
    ]
