# Generated by Django 4.2.6 on 2024-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_iin_bin_doctor_license_issued_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
