# Generated by Django 5.0.1 on 2024-03-09 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Other', max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 12, 59, 51, 303279, tzinfo=datetime.timezone.utc)),
        ),
    ]
