# Generated by Django 3.2.12 on 2024-03-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
    ]
