# Generated by Django 3.2.12 on 2024-03-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='login',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='professor',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='login',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
