# Generated by Django 3.2.12 on 2024-03-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_discipline_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.IntegerField(null=True),
        ),
    ]
