# Generated by Django 3.2.12 on 2024-03-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_news_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='speciality',
        ),
        migrations.AddField(
            model_name='discipline',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.faculty'),
        ),
    ]
