# Generated by Django 5.0.4 on 2024-05-02 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adress', models.TextField()),
                ('office_phone_number', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.familydoctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='familydoctor',
            name='work_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.hospital'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.family')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='familydoctor',
            name='personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.person'),
        ),
    ]
