# Generated by Django 5.0.1 on 2024-03-09 01:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
