# Generated by Django 5.0.1 on 2024-03-09 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_bookmark_chapter_alter_bookmark_novel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.novel'),
        ),
    ]
