# Generated by Django 4.1.5 on 2024-02-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='username',
        ),
    ]
