version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  dramatiq:
    build: .
    command: dramatiq -p 4 -t 4 core.tasks
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
