# Generated by Django 5.0.1 on 2024-03-11 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_category_alter_review_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 17, 49, 2, 771312, tzinfo=datetime.timezone.utc)),
        ),
    ]
