# Generated by Django 5.0.1 on 2024-03-11 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_price_alter_review_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('PHONES', 'Phones'), ('LAPTOP', 'Laptop'), ('TV', 'tv'), ('APPLIANCES', 'Appliances')], default='Other', max_length=40),
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 18, 4, 32, 582796, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(related_name='shops', to='main.shop'),
        ),
    ]
