# Generated by Django 5.0.3 on 2024-03-09 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_remove_userinfo_default_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busketitems',
            name='purch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.purchase'),
        ),
    ]
