# Generated by Django 5.0.3 on 2024-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_userinfo_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='busketitems',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
