# Generated by Django 5.0.3 on 2024-03-12 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_alter_purchase_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='default_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.adress'),
        ),
    ]
