version: '3.0'

services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - TZ=Asia/Almaty
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
