version: "3"

services:
  frontend:
    build: ./front
    restart: always
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: unless-stopped
    command: uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:admin@db:5432/egov
    depends_on:
      - db
  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=egov

