# Generated by Django 4.1.13 on 2024-05-12 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipe", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipe.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="measurement_quantity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipe.measurementquantity",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="measurement_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipe.measurementunit"
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipe.recipe"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipe.RecipeIngredient", to="recipe.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="direction",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directions",
                to="recipe.recipe",
            ),
        ),
    ]
