# Generated by Django 5.0.1 on 2024-03-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_city_name_airport_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="aircraft_code",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
