# Generated by Django 5.0.1 on 2024-03-11 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_days_of_week_flight_fact_flight_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight_dim",
            name="aircraft",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.aircraft",
            ),
        ),
    ]
