version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_net

volumes:
  redis_data:

networks:
  redis_net:
