# Generated by Django 4.1.7 on 2024-03-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('health', models.IntegerField(default=100)),
                ('damage', models.IntegerField(default=10)),
                ('armor', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weapon_type', models.CharField(max_length=30)),
                ('damage', models.IntegerField(default=20)),
                ('units', models.ManyToManyField(to='core.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('team', models.CharField(max_length=30)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterStrikeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.map')),
            ],
        ),
        migrations.CreateModel(
            name='Terrorist',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.player')),
                ('main_weapon', models.CharField(default='AK-47', max_length=30)),
                ('bomb_in_the_inventory', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.counterstrikegame')),
                ('weapon', models.ManyToManyField(to='core.weapon')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.player',),
        ),
        migrations.CreateModel(
            name='Hostage_or_Bot',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.unit')),
                ('main_weapon', models.CharField(default='AUG', max_length=30)),
                ('weapon', models.ManyToManyField(to='core.weapon')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.unit',),
        ),
        migrations.CreateModel(
            name='CounterTerrorist',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.player')),
                ('main_weapon', models.CharField(default='M4A4', max_length=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.counterstrikegame')),
                ('weapon', models.ManyToManyField(to='core.weapon')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.player',),
        ),
        migrations.CreateModel(
            name='Bomb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('planted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planted_bombs', to='core.terrorist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
