# Generated by Django 5.0.2 on 2024-03-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='has_criminal_issues',
            field=models.BooleanField(default=False),
        ),
    ]
