# Generated by Django 4.2.11 on 2024-03-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_customer_id_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_change_product', 'Can change product'), ('can_delete_product', 'Can delete product'), ('can_view_product', 'Can view product')]},
        ),
    ]
