# Generated by Django 5.0.2 on 2024-03-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='horsepower',
        ),
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
