# Generated by Django 4.2.11 on 2024-03-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_create_product', 'Can create product'), ('can_change_product', 'Can change product'), ('can_delete_product', 'Can delete product'), ('can_view_product', 'Can view product')]},
        ),
    ]
