# Generated by Django 5.0.2 on 2024-03-12 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_car_horsepower_car_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='populatiom',
            new_name='population',
        ),
        migrations.AddField(
            model_name='car',
            name='citizen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.citizen'),
            preserve_default=False,
        ),
    ]
