# Generated by Django 5.0.2 on 2024-03-12 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_populatiom_country_population_car_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='core.citizen'),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='core.country'),
        ),
    ]
