# Generated by Django 5.0.2 on 2024-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_car_citizen_alter_car_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='has_licence',
            field=models.BooleanField(default=True),
        ),
    ]
