# Generated by Django 4.1.7 on 2023-05-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='loc',
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
