# Generated by Django 4.1.7 on 2023-05-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tour_loc_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.location'),
        ),
    ]
