# Generated by Django 4.1.7 on 2023-05-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
