# Generated by Django 4.1.7 on 2023-05-03 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.location')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
