"""New Application, ProfileUpdateApplication table

Revision ID: 878f89d8c08f
Revises: e403dd7daf67
Create Date: 2024-05-09 15:35:45.489854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878f89d8c08f'
down_revision: Union[str, None] = 'e403dd7daf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['public.user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('profile_update_application',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.String(length=256), nullable=True),
    sa.Column('new_value', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['public.application.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'key'),
    schema='public'
    )
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_table('profile_update_application', schema='public')
    op.drop_table('application', schema='public')
    # ### end Alembic commands ###
