"""Alter status column in Application table

Revision ID: bcd9660c9343
Revises: ed7fdd3a4241
Create Date: 2024-05-11 00:07:45.856427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd9660c9343'
down_revision: Union[str, None] = 'ed7fdd3a4241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'status',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('application_user_id_fkey', 'application', type_='foreignkey')
    op.drop_constraint('application_manager_id_fkey', 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'application', 'status', ['status'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'application', 'user', ['manager_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('profile_update_application_application_id_fkey', 'profile_update_application', type_='foreignkey')
    op.create_foreign_key(None, 'profile_update_application', 'application', ['application_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_update_application', schema='public', type_='foreignkey')
    op.create_foreign_key('profile_update_application_application_id_fkey', 'profile_update_application', 'application', ['application_id'], ['id'])
    op.drop_constraint(None, 'application', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'application', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'application', schema='public', type_='foreignkey')
    op.create_foreign_key('application_manager_id_fkey', 'application', 'user', ['manager_id'], ['id'])
    op.create_foreign_key('application_user_id_fkey', 'application', 'user', ['user_id'], ['id'])
    op.alter_column('application', 'status',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)
    # ### end Alembic commands ###
