# Generated by Django 4.2.5 on 2023-10-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_identifier",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Waiting", "Waiting"),
                    ("Completed", "Completed"),
                    ("Processing", "Processing"),
                    ("Given", "Given"),
                ],
                default="Waiting",
            ),
        ),
    ]
