"""initial

Revision ID: ee8f83fdfdce
Revises: 6d9922d67540
Create Date: 2024-05-13 01:29:53.931574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8f83fdfdce'
down_revision: Union[str, None] = '6d9922d67540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipe')
    op.add_column('articles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('articles', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('articles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    op.alter_column('categories', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('comments', sa.Column('article_id', sa.Integer(), nullable=True))
    op.alter_column('comments', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('comments', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'comments', 'articles', ['article_id'], ['id'])
    op.alter_column('ingredients', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ingredients', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ingredients', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ingredients', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.alter_column('comments', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('comments', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('comments', 'article_id')
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.alter_column('articles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('articles', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('articles', 'user_id')
    op.create_table('recipe',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='recipe_pkey')
    )
    op.drop_table('recipes')
    # ### end Alembic commands ###
