FROM python:3.8

WORKDIR /django_final

COPY . /django_final

COPY requirements.txt /django_final/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main:django_final", "--host", "0.0.0.0", "--port", "8000"]



