# Generated by Django 5.0.2 on 2024-03-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midka', '0002_bookinstance_borrowed_date_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, null=True, to='midka.bookinstance'),
        ),
    ]
