# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8000/add_employee
Accept: application/json

###

GET http://127.0.0.1:8000/get_employees
###

PUT http://127.0.0.1:8000/update_employee
Accept: application/json


###

DELETE http://127.0.0.1:8000/delete_employee/123456789012
Accept: application/json