# Generated by Django 4.2.11 on 2024-03-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
    ]
